### ISSUE TITLE
GTFS import is slow

### ISSUE THREAD

**Issue by mattwigway** [conveyal/gtfs-editor#114]

**Comment by thcrock** [comment]
I have noticed this when trying to import data for Chicago. I think the import could be sped up quite a bit by using the Postgres COPY command to copy a CSV file instead of inserts. This would require some temporary disk space to create the staging file, but it may well be worth it.

It would be easier to accomplish this if the tables used a serial/bigserial column for the auto-increment id rather than a Hibernate sequence, as COPY will take care of that if the auto-increment column is omitted from the CSV.

**Comment by mattwigway** [comment]
Thanks for the suggestion. We're actually dropping postgres entirely in favor of MapDB. I actually tested the MapDB import code with Chicago GTFS last week; out was under five minutes.
		
		
		--        Matthew Wigginton Conway       Transportation Analytics/Open SourceWashington, DCindicatrix.org
		 ---- On Sun, 01 Mar 2015 00:21:12 -0500  notifications@github.com  wrote ----I have noticed this when trying to import data for Chicago. I think the import could be sped up quite a bit by using the Postgres COPY command to copy a CSV file instead of inserts. This would require some temporary disk space to create the staging file, but it may well be worth it.
It would be easier to accomplish this if the tables used a serial/bigserial column for the auto-increment id rather than a Hibernate sequence, as COPY will take care of that if the auto-increment column is omitted from the CSV.

**Comment by mattwigway** [comment]
This is fixed with latest master, which does not use Postgres at all. Note that there currently isn't a migration tool other than exporting and reimporting GTFS (or just reimporting the GTFS you started with).
