### ISSUE TITLE
Error in importing existing GTFS

### ISSUE THREAD

**Issue by agwatts** [conveyal/gtfs-editor#163]
I'm pretty sure this is from an issue in the GTFS I'm trying to import. Can anyone confirm that? More importantly, can anyone recommend a workaround, so I don't have to completely rebuild from scratch?

16:55:28.536 WARN (JDBCExceptionReporter.java:233) SQL Error: 0, SQLState: 23503
16:55:28.536 ERROR (JDBCExceptionReporter.java:234) ERROR: insert or update on table "trip" violates foreign key constraint "fk27e845434c4b3b"
  Detail: Key (servicecalendar_id)=(23245) is not present in table "servicecalendar".
16:55:28,537 ERROR ~ javax.persistence.PersistenceException: org.hibernate.exception.ConstraintViolationException: could not execute native bulk manipulation query

**Comment by mattwigway** [comment]
I actually doubt that this is due to bad GTFS, but checking that would be useful; are all service IDs in trips.txt also in calendar or calendar_dates.txt? Are there duplicate service IDs in calendar.txt?

Otherwise, it sounds like somehow the calendar isn't getting saved. This would be in jobs/ProcessGtfsSnapshotMerge.java

**Comment by mattwigway** [comment]
I think this should be fixed with latest master, which does not use Postgres at all. Note that there currently isn't a migration tool other than exporting and reimporting GTFS (or just reimporting the GTFS you started with). Feel free to reopen if it isn't.
